import type { NextConfig } from "next";
import withPWA from "@ducanh2912/next-pwa";

const nextConfig: NextConfig = {
  // Allow Three.js and shader imports
  transpilePackages: ["three"],
  // Empty turbopack config silences the "webpack config detected" warning.
  // next-pwa injects webpack config internally — this tells Next.js we know.
  turbopack: {},
};

export default withPWA({
  dest: "public",
  // Disable service worker in dev — avoids stale cache confusion while iterating
  disable: process.env.NODE_ENV === "development",
  reloadOnOnline: true,
  cacheOnFrontEndNav: true,
  // Aggressively cache static assets; be conservative with dynamic content
  workboxOptions: {
    // Remove old caches automatically when SW updates
    cleanupOutdatedCaches: true,
    // Skip waiting so new SW activates immediately on deploy
    skipWaiting: true,
    clientsClaim: true,
    runtimeCaching: [
      // ── Fonts (Google Fonts CDN) ──────────────────────────
      // Cache-First: fonts never change at a given URL, perfect for long-term caching
      {
        urlPattern: /^https:\/\/fonts\.(?:googleapis|gstatic)\.com\/.*/i,
        handler: "CacheFirst",
        options: {
          cacheName: "google-fonts",
          expiration: { maxEntries: 10, maxAgeSeconds: 60 * 60 * 24 * 365 },
          cacheableResponse: { statuses: [0, 200] },
        },
      },
      // ── Static assets: JS/CSS chunks generated by Next.js ─
      // StaleWhileRevalidate: serve from cache instantly, update in background
      {
        urlPattern: /\/_next\/static\/.*/i,
        handler: "StaleWhileRevalidate",
        options: {
          cacheName: "next-static",
          expiration: { maxEntries: 200, maxAgeSeconds: 60 * 60 * 24 * 30 },
        },
      },
      // ── Images (Next.js optimized + /icons/ + /images/) ──
      // CacheFirst: optimized images are content-hashed, safe to cache long-term
      {
        urlPattern: /\/_next\/image\?.*/i,
        handler: "CacheFirst",
        options: {
          cacheName: "next-images",
          expiration: { maxEntries: 60, maxAgeSeconds: 60 * 60 * 24 * 30 },
          cacheableResponse: { statuses: [0, 200] },
        },
      },
      {
        urlPattern: /\/icons\/.*/i,
        handler: "CacheFirst",
        options: {
          cacheName: "pwa-icons",
          expiration: { maxEntries: 20, maxAgeSeconds: 60 * 60 * 24 * 365 },
          cacheableResponse: { statuses: [0, 200] },
        },
      },
      // ── HTML pages ────────────────────────────────────────
      // NetworkFirst: always try to get fresh HTML; fall back to cache when offline
      {
        urlPattern: /^https:\/\/[^/]+\/(?!api\/).*/i,
        handler: "NetworkFirst",
        options: {
          cacheName: "pages",
          networkTimeoutSeconds: 10,
          expiration: { maxEntries: 32, maxAgeSeconds: 60 * 60 * 24 * 7 },
          cacheableResponse: { statuses: [0, 200] },
        },
      },
      // ── API routes ────────────────────────────────────────
      // NetworkOnly: never cache API responses — always fresh or fail gracefully
      {
        urlPattern: /\/api\/.*/i,
        handler: "NetworkOnly",
      },
    ],
  },
})(nextConfig);
