export interface Event {
  id: string;
  slug: string;
  artist: string;
  subtitle: string;
  date: string;
  venue: string;
  genre: string[];
  price: string;
  /** Path relative to /public — e.g. "/events/bumbum.jpg" */
  artwork?: string;
  /** Fallback gradient when no artwork */
  gradient: string;
  hasVIP: boolean;
  /** Afternoon/terrace events vs late-night main-room events */
  category: "sunset" | "night";
}

export interface GalleryItem {
  id: string;
  label: string;
  /** CSS gradient */
  gradient: string;
  /** grid span hint */
  span: "wide" | "tall" | "normal" | "large";
}

// ─────────────────────────────────────────────
// EVENTS
// ─────────────────────────────────────────────

export const EVENTS: Event[] = [
  // ── MARCH ──────────────────────────────────────────────────────────────────
  {
    id: "e1",
    slug: "fiesta-primavera",
    artist: "La Fiesta de la Primavera",
    subtitle: "Los Suruba · Thomas Patrik · Belucha",
    date: "THU 20 MAR",
    venue: "Terrace · 18:30",
    genre: ["House", "Afro", "Organic"],
    price: "From €20",
    artwork: "/events/primavera.jpg",
    gradient: "linear-gradient(135deg,#1a0800 0%,#3d1800 50%,#1a0500 100%)",
    hasVIP: true,
    category: "sunset",
  },
  {
    id: "e2",
    slug: "la-verbena",
    artist: "La Verbena Club",
    subtitle: "El Carmona · Mágico Rodriguez · Francisca Valenzuela · El Gordo Romero",
    date: "FRI 27 MAR",
    venue: "Palma City · AMOK",
    genre: ["Latin", "Urban"],
    price: "From €15",
    artwork: "/events/asset-4.png",
    gradient: "linear-gradient(135deg,#1a0000 0%,#2d0500 50%,#0d0000 100%)",
    hasVIP: false,
    category: "night",
  },
  {
    id: "e3",
    slug: "bumbum",
    artist: "BUMBUM",
    subtitle: "Grupo Icon Presenta",
    date: "SAT 28 MAR",
    venue: "Main Room",
    genre: ["Urban", "Latin"],
    price: "From €20",
    artwork: "/events/bumbum.jpg",
    gradient: "linear-gradient(135deg,#1a0010 0%,#3d0025 50%,#1a000f 100%)",
    hasVIP: true,
    category: "night",
  },
  {
    id: "e4",
    slug: "bonitx-march",
    artist: "BØNITX",
    subtitle: "#AMOKlatinnight · bumbum DJ Set",
    date: "SAT 28 MAR",
    venue: "AMOK Mallorca",
    genre: ["Latin", "Urban"],
    price: "From €20",
    artwork: "/events/asset-15.webp",
    gradient: "linear-gradient(135deg,#1a0015 0%,#300028 50%,#0d000f 100%)",
    hasVIP: true,
    category: "night",
  },
  {
    id: "e5",
    slug: "petazeta-pop",
    artist: "PetaZeta Pop",
    subtitle: "Mallorca",
    date: "SAT 28 MAR",
    venue: "AMOK",
    genre: ["Pop"],
    price: "From €15",
    artwork: "/events/asset-5.jpeg",
    gradient: "linear-gradient(135deg,#001a0a 0%,#003d1a 50%,#001a10 100%)",
    hasVIP: false,
    category: "night",
  },

  // ── APRIL ──────────────────────────────────────────────────────────────────
  {
    id: "e6",
    slug: "mentiroso-semana-santa",
    artist: "MENTIROSO",
    subtitle: "Semana Santa",
    date: "WED 1 APR",
    venue: "AMOK",
    genre: ["Pop", "Urban"],
    price: "From €15",
    artwork: "/events/asset-16.webp",
    gradient: "linear-gradient(135deg,#000a1a 0%,#001530 50%,#00080f 100%)",
    hasVIP: true,
    category: "night",
  },
  {
    id: "e7",
    slug: "santo-resacon",
    artist: "Santo Resacón",
    subtitle: "Manu Sanchez b2b Mili Takeshi · Comacattz · Alex Rasta b2b Alfonso Navarro",
    date: "THU 2 APR",
    venue: "AMOK · From 18:00",
    genre: ["House", "Electronic"],
    price: "From €15",
    artwork: "/events/asset-6.webp",
    gradient: "linear-gradient(135deg,#001020 0%,#002040 50%,#000d15 100%)",
    hasVIP: false,
    category: "sunset",
  },
  {
    id: "e8",
    slug: "toman",
    artist: "TOMAN",
    subtitle: "Manu Sanchez · Javitoh · Mili Takeshi",
    date: "THU 2 APR",
    venue: "AMOK · 23:30 – 06:00",
    genre: ["Techno", "House"],
    price: "From €20",
    artwork: "/events/asset-17.webp",
    gradient: "linear-gradient(135deg,#1a0a00 0%,#3d1800 50%,#1a0800 100%)",
    hasVIP: true,
    category: "night",
  },
  {
    id: "e9",
    slug: "chamana",
    artist: "CHAMANA",
    subtitle: "Peace, Love and House Music",
    date: "FRI 3 APR",
    venue: "AMOK · 18:00 – 23:45",
    genre: ["House", "Organic"],
    price: "From €20",
    artwork: "/events/asset-7.png",
    gradient: "linear-gradient(135deg,#1a0800 0%,#3d1500 50%,#0d0500 100%)",
    hasVIP: false,
    category: "sunset",
  },
  {
    id: "e10",
    slug: "oliver-koletzki",
    artist: "Oliver Koletzki",
    subtitle: "Dmasso (Hybrid Set) · RYD3R",
    date: "FRI 3 APR",
    venue: "AMOK · 23:00 – 06:00",
    genre: ["Techno", "House"],
    price: "From €25",
    artwork: "/events/asset-18.webp",
    gradient: "linear-gradient(135deg,#080808 0%,#161616 50%,#050505 100%)",
    hasVIP: true,
    category: "night",
  },
  {
    id: "e11",
    slug: "love-generation",
    artist: "Love Generation",
    subtitle: "El que Jallaba",
    date: "SAT 4 APR",
    venue: "AMOK · 18:08 – 23:30",
    genre: ["Pop", "Dance"],
    price: "From €15",
    artwork: "/events/asset-8.webp",
    gradient: "linear-gradient(135deg,#1a1000 0%,#302000 50%,#1a0d00 100%)",
    hasVIP: false,
    category: "sunset",
  },
  {
    id: "e12",
    slug: "bonitx-april",
    artist: "BØNITX",
    subtitle: "#AMOKlatinnight · Sábado",
    date: "SAT 4 APR",
    venue: "AMOK Mallorca",
    genre: ["Latin", "Urban"],
    price: "From €20",
    artwork: "/events/asset-19.webp",
    gradient: "linear-gradient(135deg,#1a0000 0%,#300000 50%,#0d0000 100%)",
    hasVIP: true,
    category: "night",
  },
  {
    id: "e13",
    slug: "michael-bm",
    artist: "Michael BM",
    subtitle: "Trebol",
    date: "SUN 5 APR",
    venue: "AMOK · 22:45 till late",
    genre: ["Urban"],
    price: "From €20",
    artwork: "/events/asset-20.jpeg",
    gradient: "linear-gradient(135deg,#1a1200 0%,#2d1e00 50%,#0d0a00 100%)",
    hasVIP: false,
    category: "night",
  },
  {
    id: "e14",
    slug: "mentiroso",
    artist: "MENTIROSO",
    subtitle: "Semana Santa · Uno No Basta",
    date: "THU 9 APR",
    venue: "Main Stage",
    genre: ["Pop", "Electronic"],
    price: "From €15",
    artwork: "/events/mentiroso.jpg",
    gradient: "linear-gradient(135deg,#1a0015 0%,#300025 50%,#0d000f 100%)",
    hasVIP: true,
    category: "night",
  },
  {
    id: "e15",
    slug: "polenta",
    artist: "Polenta",
    subtitle: "Mallorca",
    date: "FRI 10 APR",
    venue: "AMOK · Ctra. de S'Aranjassa KM10",
    genre: ["House", "Electronic"],
    price: "From €15",
    artwork: "/events/asset-22.webp",
    gradient: "linear-gradient(135deg,#080808 0%,#151515 50%,#050505 100%)",
    hasVIP: false,
    category: "night",
  },
  {
    id: "e16",
    slug: "claptone",
    artist: "Claptone",
    subtitle: "Jackies x NTRO",
    date: "SAT 11 APR",
    venue: "AMOK Mallorca",
    genre: ["House", "Techno"],
    price: "From €30",
    artwork: "/events/asset-9.webp",
    gradient: "linear-gradient(135deg,#1a0000 0%,#300000 50%,#0d0000 100%)",
    hasVIP: true,
    category: "night",
  },
  {
    id: "e17",
    slug: "les-castizos",
    artist: "Les Castizos",
    subtitle: "INTRO Presents · Carlos Simón · Dänny Fernandez · Jardana · Tides",
    date: "SAT 11 APR",
    venue: "AMOK · Open 00:00",
    genre: ["House", "Electronic"],
    price: "From €20",
    artwork: "/events/asset-23.webp",
    gradient: "linear-gradient(135deg,#0d0800 0%,#1a1000 50%,#080500 100%)",
    hasVIP: false,
    category: "night",
  },
  {
    id: "e18",
    slug: "j-alvarez",
    artist: "J Alvarez",
    subtitle: "Grupo Icon Presenta",
    date: "FRI 17 APR",
    venue: "AMOK",
    genre: ["Reggaeton", "Urban"],
    price: "From €25",
    artwork: "/events/asset-24.webp",
    gradient: "linear-gradient(135deg,#080808 0%,#141414 50%,#060606 100%)",
    hasVIP: true,
    category: "night",
  },
  {
    id: "e19",
    slug: "supermartxe",
    artist: "SuperMartXé",
    subtitle: "We Own The Show",
    date: "SAT 18 APR",
    venue: "AMOK Mallorca · 17:00 – 23:30",
    genre: ["Electronic", "Pop"],
    price: "From €25",
    artwork: "/events/asset-10.webp",
    gradient: "linear-gradient(135deg,#001020 0%,#002040 50%,#000d18 100%)",
    hasVIP: true,
    category: "sunset",
  },
  {
    id: "e20",
    slug: "rituale",
    artist: "RITUALË",
    subtitle: "Sunset Party",
    date: "SAT 18 APR",
    venue: "Main Room · 17:00 – 23:30",
    genre: ["House", "Electronic"],
    price: "From €20",
    artwork: "/events/asset-11.webp",
    gradient: "linear-gradient(135deg,#001a00 0%,#003300 50%,#000d00 100%)",
    hasVIP: false,
    category: "sunset",
  },
  {
    id: "e21",
    slug: "cacao",
    artist: "CACAO",
    subtitle: "Bring Your Own · Anthony Godfather · DH Moon · Purofuego · Jardana b2b Tommy",
    date: "FRI 18 APR",
    venue: "AMOK Mallorca · Open 23:30",
    genre: ["Electronic", "House"],
    price: "From €20",
    artwork: "/events/asset-25.webp",
    gradient: "linear-gradient(135deg,#1a0015 0%,#2d0020 50%,#0d000f 100%)",
    hasVIP: false,
    category: "night",
  },
  {
    id: "e22",
    slug: "superflu",
    artist: "Superflu",
    subtitle: "Cristina Tosio · Alex Caro & Sote de Lino",
    date: "FRI 24 APR",
    venue: "AMOK · 23:00 – 06:00",
    genre: ["House", "Electronic"],
    price: "From €25",
    artwork: "/events/asset-26.webp",
    gradient: "linear-gradient(135deg,#1a0000 0%,#2d0000 50%,#0d0000 100%)",
    hasVIP: true,
    category: "night",
  },
  {
    id: "e23",
    slug: "lunnas",
    artist: "LUNNAS",
    subtitle: "AMOK",
    date: "THU 30 APR",
    venue: "AMOK · 23:00 – 06:00",
    genre: ["Electronic", "Techno"],
    price: "From €20",
    artwork: "/events/asset-27.webp",
    gradient: "linear-gradient(135deg,#150000 0%,#250000 50%,#0a0000 100%)",
    hasVIP: true,
    category: "night",
  },

  // ── MAY ────────────────────────────────────────────────────────────────────
  {
    id: "e24",
    slug: "callejeo-mayo2",
    artist: "CALLEJEO",
    subtitle: "Reggaeton y Rumba",
    date: "SAT 2 MAY",
    venue: "AMOK · From 18:00",
    genre: ["Reggaeton", "Rumba"],
    price: "From €15",
    artwork: "/events/asset-12.webp",
    gradient: "linear-gradient(135deg,#0a0800 0%,#1a1400 50%,#080600 100%)",
    hasVIP: false,
    category: "sunset",
  },
  {
    id: "e25",
    slug: "callejeo-mayo30",
    artist: "CALLEJEO",
    subtitle: "Reggaeton y Rumba",
    date: "SAT 30 MAY",
    venue: "AMOK · From 18:00",
    genre: ["Reggaeton", "Rumba"],
    price: "From €15",
    artwork: "/events/asset-13.webp",
    gradient: "linear-gradient(135deg,#0a0800 0%,#1a1400 50%,#080600 100%)",
    hasVIP: false,
    category: "sunset",
  },

  // ── JUNE ───────────────────────────────────────────────────────────────────
  {
    id: "e26",
    slug: "denis-sulta",
    artist: "Denis Sulta",
    subtitle: "Priku · Jleonel · Rosana Nun",
    date: "SAT 20 JUN",
    venue: "AMOK · 23:00 – 06:00",
    genre: ["House", "Techno"],
    price: "From €35",
    artwork: "/events/asset-28.webp",
    gradient: "linear-gradient(135deg,#001015 0%,#001e28 50%,#000a10 100%)",
    hasVIP: true,
    category: "night",
  },
  {
    id: "e27",
    slug: "paul-van-dyk",
    artist: "Paul Van Dyk",
    subtitle: "Made for More · Support: Chris Bekker",
    date: "WED 25 JUN",
    venue: "AMOK · From 00:00",
    genre: ["Trance", "Electronic"],
    price: "From €30",
    artwork: "/events/asset-14.jpeg",
    gradient: "linear-gradient(135deg,#1a1000 0%,#2d1e00 50%,#0d0800 100%)",
    hasVIP: true,
    category: "night",
  },
];

// ─────────────────────────────────────────────
// GALLERY
// ─────────────────────────────────────────────

export const GALLERY: GalleryItem[] = [
  { id: "g1", label: "Terrace · Summer 24", gradient: "linear-gradient(160deg,#0d0020 0%,#2a0050 100%)", span: "wide" },
  { id: "g2", label: "Crowd · Main Stage",  gradient: "linear-gradient(160deg,#1a0500 0%,#4d1a00 100%)", span: "tall" },
  { id: "g3", label: "DJ Booth · Sunrise",  gradient: "linear-gradient(160deg,#001015 0%,#003040 100%)", span: "normal" },
  { id: "g4", label: "Pool · Golden Hour",  gradient: "linear-gradient(160deg,#200010 0%,#600030 100%)", span: "normal" },
  { id: "g5", label: "Backstage · Artists", gradient: "linear-gradient(160deg,#001a00 0%,#004d00 100%)", span: "large" },
  { id: "g6", label: "Lights · Show",       gradient: "linear-gradient(160deg,#1a1a00 0%,#4d4d00 100%)", span: "normal" },
  { id: "g7", label: "Crowd · Sunset Set",  gradient: "linear-gradient(160deg,#0a0015 0%,#20003d 100%)", span: "wide" },
  { id: "g8", label: "Terrace · Night",     gradient: "linear-gradient(160deg,#1a0a00 0%,#3d1500 100%)", span: "tall" },
];
